[package]
name = "comp-rs"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"


[lib]
name = "comp"
path = "src/lib.rs"
